config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins do
    member do
      put 'like', to:'pins#upvote'
    end
  end
  root 'pins#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user
  acts_as_votable
  has_attached_file :image, styles: { medium: "300x300#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :title, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :pins
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @pins = Pin.all.order('created_at DESC')
  end

  def new
    @pin = current_user.pins.new
  end

  def create
    @pin = current_user.pins.new(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @pin.destroy
    redirect_to root_path, notice: 'Pin was successfully deleted'
  end

  def upvote
    @pin.upvote_by current_user
    redirect_to @pin
  end

  private
  def pin_params
    params.require(:pin).permit(:title, :description, :image)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pinterest
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/shared/header'
    = render 'layouts/shared/message'
    = yield

app/views/layouts/shared/_header.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-brand= link_to "Recipe Box", root_path
    - if user_signed_in?
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "New Recipe", new_pin_path
        %li= link_to 'Sign Out', destroy_user_session_path, method: :delete
    - else
      %ul.nav.navbar-nav.navbar-right
        %li= link_to 'Sign Up', new_user_registration_path
        %li= link_to 'Sign In', new_user_session_path

app/views/layouts/shared/_message.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key}"}
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
    %ul
      %li
        = value

app/views/pins/_form.html.haml
= form_for @pin do |f|
  - if @pin.errors.any?
    %h2= pluralize(@pin.errors.count, 'error')
    %ul
      - @pin.errors.full_messages.each do |msg|
        %li= msg
  = f.label :title
  .form-group
  = f.text_field :title, class: 'form-control'
  = f.label :image
  .form-group
  = f.file_field :image
  = f.label :description
  .form-group
  = f.text_area :description, class: 'form-control'
  %br/
  = f.submit

app/views/pins/edit.html.haml
= render 'form'

app/views/pins/index.html.haml
#pins.transitions-enabled
  - @pins.each do |pin|
    .box.panel.panel-default
      = link_to (image_tag pin.image.url), pin
      %h2= link_to pin.title, pin
      %p.user
        Submitted by
        = pin.user.email

app/views/pins/new.html.haml
= render 'form'

app/views/pins/show.html.haml
#pin_show.row
  .col-md-8.col-md-offset-2
    .panel.panel-default
      .panel-heading.pin_image
        = image_tag @pin.image.url
      .panel-body
        %h1= @pin.title
        %p.description= @pin.description
      .panel-footer
        .row
          .col-md-6
            %p.user
              Submitted by
              = @pin.user.email
          .col-md-6
            .btn-group.pull-right
              = link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do
                %span.glyphicon.glyphicon-heart
                = @pin.get_upvotes.size
              - if user_signed_in?
                = link_to "Edit", edit_pin_path, class: "btn btn-default"
                = link_to 'destroy', pin_path(@pin), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>